# Generated by Django 4.2.27 on 2026-01-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='products/')),
                ('sell_unit', models.CharField(choices=[('kg', 'بالكيلوغرام'), ('piece', 'بالقطعة')], default='kg', max_length=10)),
                ('price', models.FloatField(help_text='السعر للوحدة (كغ أو قطعة)')),
                ('step', models.FloatField(default=0.5, help_text='مثلا 0.5 كغ أو 1 قطعة')),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
